spring:
  config:
    activate:
      on-profile: dev

  rabbitmq:
    host: localhost
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false

  datasource:
    dbcp2:
      validation-query: SELECT 1
      initial-size: 20
      max-idle: 10
      min-idle: 1
      max-total: 200
      test-on-borrow: true
      test-while-idle: true
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/boradoo
#    username: root
#    password: 1234
    url: jdbc:mysql://133.186.241.167:3306/be6_yes255_order
    username: be6_yes255
    password: ${YES25_5_MYSQL_PASSWORD}
    type: org.apache.commons.dbcp2.BasicDataSource

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
        default_batch_fetch_size: 500
    database: mysql
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  application:
    name: order-payment-server

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration: debug
    org.springframework.amqp.rabbit.listener: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace
  file:
    path: ${user.dir}/logs/${spring.application.name}

server:
  port: 8071

eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

api:
  books-users: http://127.0.0.1:8061
  coupon: http://127.0.0.1:8081

logHost: localhost
