spring:
  rabbitmq:
    host: 133.186.241.167
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 5
          multiplier: 1.5
        default-requeue-rejected: false
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        multiplier: 1.5
    username: admin
    password: ${RABBITMQ_PASSWORD}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/be6_yes255_order
    type: org.apache.commons.dbcp2.BasicDataSource
    username: be6_yes255
    password: ${YES25_5_MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    database: mysql
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  data:
    redis:
      host: 133.186.241.167
      port: 6379
      database: 34
      password: ${YES25_5_REDIS_PASSWORD}
  application:
    name: order-payment-server
logging:
  level:
    org.springframework.amqp.rabbit.listener: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace
  file:
    path: ${user.home}/logs/${spring.application.name}
eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka/
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME}

jwt:
  secret: ${JWT_SECRET}
api:
  books-users: http://localhost:8061
  coupon: http://localhost:8081

payment:
  secret: ${PAYMENT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health, info