spring:
  profiles:
    active: dev

  data:
    redis:
      host: 133.186.241.167
      port: 6379
      database: 18
      password: "*N2vya7H@muDTwdNMR!"

nhn:
  cloud:
    secure:
      url: https://api-keymanager.nhncloudservice.com/keymanager/v1.0/appkey/2SxwmBzUfnqJaA2A
      mysql: a8924de0e1444ac38698160ebacad5e5

payment:
  secret: ${PAYMENT_SECRET}

jwt:
  secret: ${JWT_SECRET}