spring:
  rabbitmq:
    host: 133.186.153.195
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 5
          multiplier: 1.5
        default-requeue-rejected: false
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        multiplier: 1.5
    username: yes255
    password: yes255

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/be6_yes255_order
    username: be6_yes255
    password: ${YES25_5_MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    database: mysql
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  data:
    redis:
      host: 133.186.241.167
      port: 6379
      database: 34
      password: ${YES25_5_REDIS_PASSWORD}
  application:
    name: order-payment-server
logging:
  level:
    org.springframework.amqp.rabbit.listener: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace
server:
  port: 8071
eureka:
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka/

jwt:
  secret: ${JWT_SECRET}
api:
  books-users: ${BOOK_USER_SERVER}
  coupon: ${COUPON_SERVER}

payment:
  secret: ${PAYMENT_SECRET}