spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/nhn_academy_34
    username: nhn_academy_34
    password: ${YES25_5_MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    database: mysql
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: 133.186.241.167
      port: 6379
      database: 34
      password: ${YES25_5_REDIS_PASSWORD}
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace
server:
  port: 8070
eureka:
  client:
    enabled: false
    fetchRegistry: false
    registerWithEureka: false

jwt:
  secret: this-is-secret-key-yeah-ho-hu-yea-yes-hi-bye