spring:
  rabbitmq:
    host: localhost
    port: 5672

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/be6_yes255
    username: be6_yes255
    password: ${YES25_5_MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    database: mysql
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: 133.186.241.167
      port: 6379
      database: 34
      password: ${YES25_5_REDIS_PASSWORD}
  application:
    name: order-payment-server
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace
server:
  port: 8071
eureka:
  client:
    enabled: false
    fetchRegistry: false
    registerWithEureka: false
#    enabled: true
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: this-is-secret-key-yeah-ho-hu-yea-yes-hi-bye