spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/nhn_academy_16
    username: nhn_academy_16
    password: ${{ secrets.MYSQL_PASSWORD }}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    database: mysql
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: "133.186.241.167"
      port: 6379
      database: 34
      password: ${{ secrets.MYSQL_PASSWORD }}
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace

#jwt:
#  secret: my-very-secure-and-long-secret-key-here-ha-ho-ye-a
#  expiration: 86400000


server:
  port: 8786

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true