spring:
  profiles:
    active: dev

  data:
    redis:
      host: 133.186.241.167
      port: 6379
      database: 18
      password: "*N2vya7H@muDTwdNMR!"

nhn:
  cloud:
    secure:
      url: https://api-keymanager.nhncloudservice.com/keymanager/v1.0/appkey/2SxwmBzUfnqJaA2A

payment:
  secret: da24787c30d9427fbcc02b28b244301b

jwt:
  secret: e665cfbd55854ea5bd66bac1607e016c